artifact_location: /Users/thidaratchuram/Documents/GitHub/MLops-City/runs/mlflow/373285327870057626
creation_time: 1778610693435
experiment_id: '373285327870057626'
last_update_time: 1778610693435
lifecycle_stage: active
name: traffic_yolo
trace_location: null
workspace: default
